import { Request, Response } from 'express';
import { parse } from 'qs';

function getillCase(req: Request, res: Response, u: string) {
  let realUrl = u;
  if (
    !realUrl ||
    Object.prototype.toString.call(realUrl) !== '[object String]'
  ) {
    realUrl = req.url;
  }
  const { id = -1 } = req.query;
  const params = parse(realUrl, true).query as unknown;
  if (id == -1) {
    const result = {
      code: 4056,
    };
    return res.json(result);
  }

  const result = {
    code: 200,
    data: {
      DetailTrePlan: [
        {
          begDate: '2020-07-13',
          currPeriod: 1,
          drugs: {
            紫杉醇: {
              drugDosa: 1,
              unit: 'g',
            },
          },
          endDate: '2020-07-06',
          id: 3,
          pid: 2,
          treNum: 1,
          treSche: '常用药物',
          treSolu: 'Chemotherapy',
          treatName: 'xxx1',
        },
      ],
      FollInfo: [
        {
          date: 'Wed, 08 Jul 2020 00:00:00 GMT',
          effEva: 3,
          examArea: null,
          folMet: 2,
          id: 1,
          imaFilType: '2',
          livSta: 2,
          number: 0,
          pid: 16,
          remarks: null,
          savFilPath: 'static/16/icon_48.png',
          tumorDesc: null,
          tumorLD: null,
          tumorSD: null,
        },
      ],
      ImageExams: [
        {
          detectTime: '2020-08-01',
          examArea: '1',
          exmaMethod: 'MRI,CT',
          tumorLD: '1',
          tumorSD: '1',
          tumorDesc: '1',
          path: '1',
        },
        {
          detectTime: '2020-08-01',
          examArea: '1',
          exmaMethod: 'MRI,CT',
          tumorLD: '1',
          tumorSD: '1',
          tumorDesc: '1',
          path: '1',
        },
      ],
      Immunohis: [
        {
          ALKD5F3: null,
          ALKD5F3N: null,
          CAIX: null,
          CAM52: null,
          CD10: null,
          CD117: null,
          CD34: null,
          CD56: null,
          CDX2: null,
          CEA: null,
          CK: null,
          CK19: null,
          CK20: null,
          CK56: null,
          CK7: null,
          CK818: 2,
          CgA: null,
          Cyn: null,
          DLL3: null,
          EMA: null,
          ERCC1: null,
          LCA: null,
          MCM2: null,
          NapsinA: null,
          P16: null,
          P40: null,
          P63: null,
          PAX2: null,
          PAX8: null,
          PCK: null,
          PDL1: null,
          RRM1: null,
          SATB2: null,
          Syn: null,
          TTF1: null,
          VEGFC: null,
          Villin: 2,
          Villinco: null,
          id: 2,
          other: null,
          p53: null,
          pid: 1,
          treNum: 0,
        },
      ],
      IniDiaPro: [
        {
          Ki67: null,
          PSScore: 0,
          TSize: null,
          bioMet: '',
          cStage: null,
          cliStage: null,
          cliniManifest: null,
          comCar: null,
          firVisDate: null,
          id: 1,
          massSize: null,
          mitIma: null,
          necArea: null,
          pStage: null,
          part: '',
          patDia: '',
          patNum: null,
          patReDate: null,
          patStage: null,
          pid: 16,
          pleInv: null,
          speSite: null,
          stage: null,
          traSite: '',
          videography: null,
        },
      ],
      MoleDetec: [
        {
          ALK: null,
          ALKDesc: null,
          ALKDetMed: null,
          ALKSam: null,
          BIM: 0,
          BIMDesc: null,
          BIMDetMed: null,
          BIMSam: null,
          BRAF: 1,
          BRAFDesc: null,
          BRAFDetMed: 2,
          BRAFSam: '1',
          EGFR: null,
          EGFRDesc: null,
          EGFRDetMed: null,
          EGFRSam: null,
          HER_2: null,
          HER_2Desc: null,
          HER_2DetMed: null,
          HER_2Sam: null,
          HER_2_co: null,
          HER_2_coDesc: null,
          HER_2_coDetMed: null,
          HER_2_coSam: null,
          MSI: null,
          PDL1: 1,
          PIK3CA: null,
          PIK3CADesc: null,
          PIK3CADetMed: null,
          PIK3CASam: null,
          RET: null,
          RETDesc: null,
          RETDetMed: null,
          RETSam: null,
          ROS1: null,
          ROS1Desc: null,
          ROS1DetMed: null,
          ROS1Sam: null,
          TMB: null,
          UGT1A1: null,
          UGT1A1Desc: null,
          UGT1A1DetMed: null,
          UGT1A1Sam: null,
          cMET: null,
          cMETDesc: null,
          cMETDetMed: null,
          cMETSam: null,
          id: 2,
          path: 'static/16/icon_48.png,static/16/icon_16.png',
          pid: 1,
          treNum: null,
        },
      ],
      OneToFive: [
        {
          begDate: '2020-07-14',
          bioMet: '1',
          clinTri: null,
          endDate: '2020-07-07',
          id: 4,
          isRepBio: true,
          isTre: 1,
          matPart: '2',
          patDiaRes: '4',
          pid: 2,
          spePlan: null,
          specNum: 3,
          treNum: 1,
          treSolu: 'Chemotherapy',
        },
      ],
      OtherExams: [
        {
          ECGDetTime: '2020-07-07',
          ECGDesc: '1',
          ECGPath: '1',
          UCGDetTime: '2020-07-09',
          UCGDesc: '1',
          UCGPath: '1',
        },
        {
          ECGDetTime: '2020-07-07',
          ECGDesc: '1',
          ECGPath: '1',
          UCGDetTime: '2020-07-09',
          UCGDesc: '1',
          UCGPath: '1',
        },
      ],
      Patient: [
        {
          account: ',54,',
          birthday: 'Thu, 16 Jul 2020 00:00:00 GMT',
          gender: '1',
          hospitalNumber: '12331211',
          id: 3,
          idNumber: '123456200001012234',
          patientName: 'test3',
          phoneNumber1: 12441355,
          phoneNumber2: null,
          researchCenter: ',17,',
          updateTime: null,
        },
      ],
      Radiotherapy: [
        {
          begDate: '2020-07-13',
          dosUnit: 0,
          endDate: '2020-07-14',
          id: 1,
          pid: 2,
          radDose: 1.0,
          radSite: ['\u8111', '\u9501\u9aa8\u4e0a'],
          splTim: 1,
          treNum: 1,
        },
      ],
      SideEffect: [
        {
          begDate: '2020-07-16',
          endDate: '2020-07-20',
          id: 1,
          isExe: false,
          pid: 2,
          sidReaName: '循环系统副作用,心率失常',
          sidRecCla: 2,
          treNum: 1,
        },
        {
          begDate: '2020-07-06',
          endDate: '2020-07-19',
          id: 2,
          isExe: false,
          pid: 2,
          sidReaName: '呼吸系统副作用,呼吸系统纤维化',
          sidRecCla: 2,
          treNum: 1,
        },
      ],
      Signs: [
        {
          begDate: '2020-07-20',
          endDate: '2020-07-16',
          id: 1,
          isExe: false,
          pid: 2,
          symName: '12',
          treNum: 1,
        },
      ],
      Surgery: [
        {
          cleGro: null,
          id: 1,
          isPro: null,
          lymDis: ['系统性清扫', '取样'],
          pid: 2,
          posAdjChem: true,
          proDate: null,
          proDes: null,
          surDate: '2020-07-15',
          surSco: ['肺叶', '双肺叶'],
          treNum: 1,
        },
      ],
      TreRec: [
        {
          beEffEva: '1',
          beEffEvaDate: '2020-07-16',
          date: null,
          id: 5,
          pid: 2,
          proDate: '2020-07-07',
          proDes: 'e2e22ee2e',
          treNum: 1,
          //trement: 'surgery',
          //trement: 'radiotherapy',
          trement: 'one',
        },
      ],
      BloodRoutine: [
        {
          RBC: '1',
          HGb: '1',
          HCT: '1',
          MCV: '1',
          MCH: '1',
          MCHC: '1',
          RDWCV: '1',
          RDWSD: '1',
          WBC: '1',
          GRAN_: '1',
          LYM_: '1',
          EOS_: '1',
          MID_: '1',
          BASO_: '1',
          PLT: '1',
          LYM: '1',
          MID: '1',
          GRAN: '1',
          EOS: '1',
          BASO: '1',
          NEUT: '1',
          RBCMea: '1',
          HGbMea: '1',
          HCTMea: '1',
          MCVMea: '1',
          MCHMea: '1',
          MCHCMea: '1',
          RDWCVMea: '1',
          RDWSDMea: '1',
          WBCMea: '1',
          GRAN_Mea: '1',
          LYM_Mea: '1',
          EOS_Mea: '1',
          MID_Mea: '1',
          BASO_Mea: '1',
          PLTMea: '1',
          LYMMea: '1',
          MIDMea: '1',
          EOSMea: '1',
          BASOMea: '1',
          NEUTMea: '1',
          RBCNote: '1',
          HGbNote: '1',
          HCTNote: '1',
          MCVNote: '1',
          MCHNote: '1',
          MCHCNote: '1',
          RDWCVNote: '1',
          RDWSDNote: '1',
          WBCNote: '1',
          GRAN_Note: '1',
          LYM_Note: '1',
          EOS_Note: '1',
          MID_Note: '1',
          BASO_Note: '1',
          PLTNote: '1',
          LYMNote: '1',
          MIDNote: '1',
          GRANNote: '1',
          EOSNote: '1',
          BASONote: '1',
          NEUTNote: '1',
        },
        {
          RBC: '1',
          HGb: '1',
          HCT: '1',
          MCV: '1',
          MCH: '1',
          MCHC: '1',
          RDWCV: '1',
          RDWSD: '1',
          WBC: '1',
          GRAN_: '1',
          LYM_: '1',
          EOS_: '1',
          MID_: '1',
          BASO_: '1',
          PLT: '1',
          LYM: '1',
          MID: '1',
          GRAN: '1',
          EOS: '1',
          BASO: '1',
          NEUT: '1',
          RBCMea: '1',
          HGbMea: '1',
          HCTMea: '1',
          MCVMea: '1',
          MCHMea: '1',
          MCHCMea: '1',
          RDWCVMea: '1',
          RDWSDMea: '1',
          WBCMea: '1',
          GRAN_Mea: '1',
          LYM_Mea: '1',
          EOS_Mea: '1',
          MID_Mea: '1',
          BASO_Mea: '1',
          PLTMea: '1',
          LYMMea: '1',
          MIDMea: '1',
          EOSMea: '1',
          BASOMea: '1',
          NEUTMea: '1',
          RBCNote: '1',
          HGbNote: '1',
          HCTNote: '1',
          MCVNote: '1',
          MCHNote: '1',
          MCHCNote: '1',
          RDWCVNote: '1',
          RDWSDNote: '1',
          WBCNote: '1',
          GRAN_Note: '1',
          LYM_Note: '1',
          EOS_Note: '1',
          MID_Note: '1',
          BASO_Note: '1',
          PLTNote: '1',
          LYMNote: '1',
          MIDNote: '1',
          GRANNote: '1',
          EOSNote: '1',
          BASONote: '1',
          NEUTNote: '1',
        },
      ],

      BloodBio: [
        {
          TP: '1',
          ALB: '1',
          GLO: '1',
          ALT: '1',
          AST: '1',
          LDH: '1',
          GGT: '1',
          TBIL: '1',
          DBIL: '1',
          IBIL: '1',
          GLU: '1',
          TC: '1',
          LDL: '1',
          hDL: '1',
          TG: '1',
          UREA: '1',
          ALP: '1',
          CREA: '1',
          UA: '1',
          CO2: '1',
          K: '1',
          Na: '1',
          Cl: '1',
          Ca: '1',
          Mg: '1',
          P: '1',
          TPMea: '1',
          ALBMea: '1',
          GLOMea: '1',
          ALTMea: '1',
          ASTMea: '1',
          LDHMea: '1',
          GGTMea: '1',
          TBILMea: '1',
          DBILMea: '1',
          IBILMea: '1',
          GLUMea: '1',
          TCMea: '1',
          LDLMea: '1',
          hDLMea: '1',
          TGMea: '1',
          UREAMea: '1',
          ALPMea: '1',
          CREAMea: '1',
          UAMea: '1',
          CO2Mea: '1',
          KMea: '1',
          NaMea: '1',
          ClMea: '1',
          CaMea: '1',
          MgMea: '1',
          PMea: '1',
          TPNote: '1',
          ALBNote: '1',
          GLONote: '1',
          ALTNote: '1',
          ASTNote: '1',
          LDHNote: '1',
          GGTNote: '1',
          TBILNote: '1',
          DBILNote: '1',
          IBILNote: '1',
          GLUNote: '1',
          TCNote: '1',
          LDLNote: '1',
          hDLNote: '1',
          TGNote: '1',
          UREANote: '1',
          ALPNote: '1',
          CREANote: '1',
          UANote: '1',
          CO2Note: '1',
          KNote: '1',
          NaNote: '1',
          ClNote: '1',
          CaNote: '1',
          MgNote: '1',
          PNote: '1',
        },
        {
          TP: '1',
          ALB: '1',
          GLO: '1',
          ALT: '1',
          AST: '1',
          LDH: '1',
          GGT: '1',
          TBIL: '1',
          DBIL: '1',
          IBIL: '1',
          GLU: '1',
          TC: '1',
          LDL: '1',
          hDL: '1',
          TG: '1',
          UREA: '1',
          ALP: '1',
          CREA: '1',
          UA: '1',
          CO2: '1',
          K: '1',
          Na: '1',
          Cl: '1',
          Ca: '1',
          Mg: '1',
          P: '1',
          TPMea: '1',
          ALBMea: '1',
          GLOMea: '1',
          ALTMea: '1',
          ASTMea: '1',
          LDHMea: '1',
          GGTMea: '1',
          TBILMea: '1',
          DBILMea: '1',
          IBILMea: '1',
          GLUMea: '1',
          TCMea: '1',
          LDLMea: '1',
          hDLMea: '1',
          TGMea: '1',
          UREAMea: '1',
          ALPMea: '1',
          CREAMea: '1',
          UAMea: '1',
          CO2Mea: '1',
          KMea: '1',
          NaMea: '1',
          ClMea: '1',
          CaMea: '1',
          MgMea: '1',
          PMea: '1',
          TPNote: '1',
          ALBNote: '1',
          GLONote: '1',
          ALTNote: '1',
          ASTNote: '1',
          LDHNote: '1',
          GGTNote: '1',
          TBILNote: '1',
          DBILNote: '1',
          IBILNote: '1',
          GLUNote: '1',
          TCNote: '1',
          LDLNote: '1',
          hDLNote: '1',
          TGNote: '1',
          UREANote: '1',
          ALPNote: '1',
          CREANote: '1',
          UANote: '1',
          CO2Note: '1',
          KNote: '1',
          NaNote: '1',
          ClNote: '1',
          CaNote: '1',
          MgNote: '1',
          PNote: '1',
        },
      ],

      Thyroid: [
        {
          FT3: '1',
          FT4: '1',
          TSH: '1',
          FT3Mea: '1',
          FT4Mea: '1',
          TSHMea: '1',
          FT3Note: '1',
          FT4Note: '1',
          TSHNote: '1',
        },
        {
          FT3: '1',
          FT4: '1',
          TSH: '1',
          FT3Mea: '1',
          FT4Mea: '1',
          TSHMea: '1',
          FT3Note: '1',
          FT4Note: '1',
          TSHNote: '1',
        },
      ],

      Coagulation: [
        {
          PT: '1',
          APTT: '1',
          TT: '1',
          FIB: '1',
          INR: '1',
          D_dimer: '1',
          PTMea: '1',
          APTTMea: '1',
          TTMea: '1',
          FIBMea: '1',
          INRMea: '1',
          D_dimer_Mea: '1',
          PTNote: '1',
          APTTNote: '1',
          TTNote: '1',
          FIBNote: '1',
          INRNote: '1',
          D_dimer_Note: '1',
        },
        {
          PT: '1',
          APTT: '1',
          TT: '1',
          FIB: '1',
          INR: '1',
          D_dimer: '1',
          PTMea: '1',
          APTTMea: '1',
          TTMea: '1',
          FIBMea: '1',
          INRMea: '1',
          D_dimer_Mea: '1',
          PTNote: '1',
          APTTNote: '1',
          TTNote: '1',
          FIBNote: '1',
          INRNote: '1',
          D_dimer_Note: '1',
        },
      ],

      MyocardialEnzyme: [
        {
          LDH: '1',
          CK: '1',
          CK_MB: '1',
          cTnI: '1',
          cTnT: '1',
          MYO: '1',
          BNP: '1',
          NT_proBNP: '1',
          LDHMea: '1',
          CKMea: '1',
          CK_MBMea: '1',
          cTnIMea: '1',
          cTnTMea: '1',
          MYOMea: '1',
          BNPMea: '1',
          NT_proBNPMea: '1',
          LDHNote: '1',
          CKNote: '1',
          CK_MBNote: '1',
          cTnINote: '1',
          cTnTNote: '1',
          MYONote: '1',
          BNPNote: '1',
          NT_proBNPNote: '1',
        },
        {
          LDH: '1',
          CK: '1',
          CK_MB: '1',
          cTnI: '1',
          cTnT: '1',
          MYO: '1',
          BNP: '1',
          NT_proBNP: '1',
          LDHMea: '1',
          CKMea: '1',
          CK_MBMea: '1',
          cTnIMea: '1',
          cTnTMea: '1',
          MYOMea: '1',
          BNPMea: '1',
          NT_proBNPMea: '1',
          LDHNote: '1',
          CKNote: '1',
          CK_MBNote: '1',
          cTnINote: '1',
          cTnTNote: '1',
          MYONote: '1',
          BNPNote: '1',
          NT_proBNPNote: '1',
        },
      ],

      Cytokines: [
        {
          TNF_a: '1',
          IL_1b: '1',
          IL_2R: '1',
          IL_6: '1',
          IL_8: '1',
          IL_10: '1',
          TNF_aMea: '1',
          IL_1bMea: '1',
          IL_2RMea: '1',
          IL_6Mea: '1',
          IL_8Mea: '1',
          IL_10Mea: '1',
          TNF_aNote: '1',
          IL_1bNote: '1',
          IL_2RNote: '1',
          IL_6Note: '1',
          IL_8Note: '1',
          IL_10Note: '1',
        },
        {
          TNF_a: '1',
          IL_1b: '1',
          IL_2R: '1',
          IL_6: '1',
          IL_8: '1',
          IL_10: '1',
          TNF_aMea: '1',
          IL_1bMea: '1',
          IL_2RMea: '1',
          IL_6Mea: '1',
          IL_8Mea: '1',
          IL_10Mea: '1',
          TNF_aNote: '1',
          IL_1bNote: '1',
          IL_2RNote: '1',
          IL_6Note: '1',
          IL_8Note: '1',
          IL_10Note: '1',
        },
      ],

      LymSubsets: [
        {
          CD19_: '1',
          CD3_: '1',
          CD4_: '1',
          CD8_: '1',
          CD16_56: '1',
          LYMPH_: '1',
          CD19: '1',
          CD3: '1',
          CD4: '1',
          CD8: '1',
          CD4CD8: '1',
          CD56: '1',
          CD3_CD8__: '1',
          CD3_CD8_: '1',
          CD3_CD4__: '1',
          CD3_CD4_: '1',
          CD3_CD16_56_: '1',
          CD3_CD16_56: '1',
          CD3_CD19__: '1',
          CD3_CD19_: '1',
          CD8_CD28_: '1',
          CD20_: '1',
          HLA_DR_: '1',
          CD3_HLA_DR1: '1',
          CD3_HLA_DR2: '1',
          CD3_HLA_DR3: '1',
          CD4_CD25_CD127low: '1',
          CD19_Mea: '1',
          CD3_Mea: '1',
          CD4_Mea: '1',
          CD8_Mea: '1',
          CD16_56Mea: '1',
          LYMPH_Mea: '1',
          CD19Mea: '1',
          CD3Mea: '1',
          CD4Mea: '1',
          CD8Mea: '1',
          CD4CD8Mea: '1',
          CD56Mea: '1',
          CD3_CD8__Mea: '1',
          CD3_CD8_Mea: '1',
          CD3_CD4__Mea: '1',
          CD3_CD4_Mea: '1',
          CD3_CD16_56_Mea: '1',
          CD3_CD16_56Mea: '1',
          CD3_CD19__Mea: '1',
          CD3_CD19_Mea: '1',
          CD8_CD28_Mea: '1',
          CD20_Mea: '1',
          HLA_DR_Mea: '1',
          CD3_HLA_DR1Mea: '1',
          CD3_HLA_DR2Mea: '1',
          CD3_HLA_DR3Mea: '1',
          CD4_CD25_CD127lowMea: '1',
          CD19_Note: '1',
          CD3_Note: '1',
          CD4_Note: '1',
          CD8_Note: '1',
          CD16_56Note: '1',
          LYMPH_Note: '1',
          CD19Note: '1',
          CD3Note: '1',
          CD4Note: '1',
          CD8Note: '1',
          CD4CD8Note: '1',
          CD56Note: '1',
          CD3_CD8__Note: '1',
          CD3_CD8_Note: '1',
          CD3_CD4__Note: '1',
          CD3_CD4_Note: '1',
          CD3_CD16_56_Note: '1',
          CD3_CD16_56Note: '1',
          CD3_CD19__Note: '1',
          CD3_CD19_Note: '1',
          CD8_CD28_Note: '1',
          CD20_Note: '1',
          HLA_DR_Note: '1',
          CD3_HLA_DR1Note: '1',
          CD3_HLA_DR2Note: '1',
          CD3_HLA_DR3Note: '1',
          CD4_CD25_CD127lowNote: '1',
        },
        {
          CD19_: '1',
          CD3_: '1',
          CD4_: '1',
          CD8_: '1',
          CD16_56: '1',
          LYMPH_: '1',
          CD19: '1',
          CD3: '1',
          CD4: '1',
          CD8: '1',
          CD4CD8: '1',
          CD56: '1',
          CD3_CD8__: '1',
          CD3_CD8_: '1',
          CD3_CD4__: '1',
          CD3_CD4_: '1',
          CD3_CD16_56_: '1',
          CD3_CD16_56: '1',
          CD3_CD19__: '1',
          CD3_CD19_: '1',
          CD8_CD28_: '1',
          CD20_: '1',
          HLA_DR_: '1',
          CD3_HLA_DR1: '1',
          CD3_HLA_DR2: '1',
          CD3_HLA_DR3: '1',
          CD4_CD25_CD127low: '1',
          CD19_Mea: '1',
          CD3_Mea: '1',
          CD4_Mea: '1',
          CD8_Mea: '1',
          CD16_56Mea: '1',
          LYMPH_Mea: '1',
          CD19Mea: '1',
          CD3Mea: '1',
          CD4Mea: '1',
          CD8Mea: '1',
          CD4CD8Mea: '1',
          CD56Mea: '1',
          CD3_CD8__Mea: '1',
          CD3_CD8_Mea: '1',
          CD3_CD4__Mea: '1',
          CD3_CD4_Mea: '1',
          CD3_CD16_56_Mea: '1',
          CD3_CD16_56Mea: '1',
          CD3_CD19__Mea: '1',
          CD3_CD19_Mea: '1',
          CD8_CD28_Mea: '1',
          CD20_Mea: '1',
          HLA_DR_Mea: '1',
          CD3_HLA_DR1Mea: '1',
          CD3_HLA_DR2Mea: '1',
          CD3_HLA_DR3Mea: '1',
          CD4_CD25_CD127lowMea: '1',
          CD19_Note: '1',
          CD3_Note: '1',
          CD4_Note: '1',
          CD8_Note: '1',
          CD16_56Note: '1',
          LYMPH_Note: '1',
          CD19Note: '1',
          CD3Note: '1',
          CD4Note: '1',
          CD8Note: '1',
          CD4CD8Note: '1',
          CD56Note: '1',
          CD3_CD8__Note: '1',
          CD3_CD8_Note: '1',
          CD3_CD4__Note: '1',
          CD3_CD4_Note: '1',
          CD3_CD16_56_Note: '1',
          CD3_CD16_56Note: '1',
          CD3_CD19__Note: '1',
          CD3_CD19_Note: '1',
          CD8_CD28_Note: '1',
          CD20_Note: '1',
          HLA_DR_Note: '1',
          CD3_HLA_DR1Note: '1',
          CD3_HLA_DR2Note: '1',
          CD3_HLA_DR3Note: '1',
          CD4_CD25_CD127lowNote: '1',
        },
        {
          CD19_: '1',
          CD3_: '1',
          CD4_: '1',
          CD8_: '1',
          CD16_56: '1',
          LYMPH_: '1',
          CD19: '1',
          CD3: '1',
          CD4: '1',
          CD8: '1',
          CD4CD8: '1',
          CD56: '1',
          CD3_CD8__: '1',
          CD3_CD8_: '1',
          CD3_CD4__: '1',
          CD3_CD4_: '1',
          CD3_CD16_56_: '1',
          CD3_CD16_56: '1',
          CD3_CD19__: '1',
          CD3_CD19_: '1',
          CD8_CD28_: '1',
          CD20_: '1',
          HLA_DR_: '1',
          CD3_HLA_DR1: '1',
          CD3_HLA_DR2: '1',
          CD3_HLA_DR3: '1',
          CD4_CD25_CD127low: '1',
          CD19_Mea: '1',
          CD3_Mea: '1',
          CD4_Mea: '1',
          CD8_Mea: '1',
          CD16_56Mea: '1',
          LYMPH_Mea: '1',
          CD19Mea: '1',
          CD3Mea: '1',
          CD4Mea: '1',
          CD8Mea: '1',
          CD4CD8Mea: '1',
          CD56Mea: '1',
          CD3_CD8__Mea: '1',
          CD3_CD8_Mea: '1',
          CD3_CD4__Mea: '1',
          CD3_CD4_Mea: '1',
          CD3_CD16_56_Mea: '1',
          CD3_CD16_56Mea: '1',
          CD3_CD19__Mea: '1',
          CD3_CD19_Mea: '1',
          CD8_CD28_Mea: '1',
          CD20_Mea: '1',
          HLA_DR_Mea: '1',
          CD3_HLA_DR1Mea: '1',
          CD3_HLA_DR2Mea: '1',
          CD3_HLA_DR3Mea: '1',
          CD4_CD25_CD127lowMea: '1',
          CD19_Note: '1',
          CD3_Note: '1',
          CD4_Note: '1',
          CD8_Note: '1',
          CD16_56Note: '1',
          LYMPH_Note: '1',
          CD19Note: '1',
          CD3Note: '1',
          CD4Note: '1',
          CD8Note: '1',
          CD4CD8Note: '1',
          CD56Note: '1',
          CD3_CD8__Note: '1',
          CD3_CD8_Note: '1',
          CD3_CD4__Note: '1',
          CD3_CD4_Note: '1',
          CD3_CD16_56_Note: '1',
          CD3_CD16_56Note: '1',
          CD3_CD19__Note: '1',
          CD3_CD19_Note: '1',
          CD8_CD28_Note: '1',
          CD20_Note: '1',
          HLA_DR_Note: '1',
          CD3_HLA_DR1Note: '1',
          CD3_HLA_DR2Note: '1',
          CD3_HLA_DR3Note: '1',
          CD4_CD25_CD127lowNote: '1',
        },
        {
          CD19_: '1',
          CD3_: '1',
          CD4_: '1',
          CD8_: '1',
          CD16_56: '1',
          LYMPH_: '1',
          CD19: '1',
          CD3: '1',
          CD4: '1',
          CD8: '1',
          CD4CD8: '1',
          CD56: '1',
          CD3_CD8__: '1',
          CD3_CD8_: '1',
          CD3_CD4__: '1',
          CD3_CD4_: '1',
          CD3_CD16_56_: '1',
          CD3_CD16_56: '1',
          CD3_CD19__: '1',
          CD3_CD19_: '1',
          CD8_CD28_: '1',
          CD20_: '1',
          HLA_DR_: '1',
          CD3_HLA_DR1: '1',
          CD3_HLA_DR2: '1',
          CD3_HLA_DR3: '1',
          CD4_CD25_CD127low: '1',
          CD19_Mea: '1',
          CD3_Mea: '1',
          CD4_Mea: '1',
          CD8_Mea: '1',
          CD16_56Mea: '1',
          LYMPH_Mea: '1',
          CD19Mea: '1',
          CD3Mea: '1',
          CD4Mea: '1',
          CD8Mea: '1',
          CD4CD8Mea: '1',
          CD56Mea: '1',
          CD3_CD8__Mea: '1',
          CD3_CD8_Mea: '1',
          CD3_CD4__Mea: '1',
          CD3_CD4_Mea: '1',
          CD3_CD16_56_Mea: '1',
          CD3_CD16_56Mea: '1',
          CD3_CD19__Mea: '1',
          CD3_CD19_Mea: '1',
          CD8_CD28_Mea: '1',
          CD20_Mea: '1',
          HLA_DR_Mea: '1',
          CD3_HLA_DR1Mea: '1',
          CD3_HLA_DR2Mea: '1',
          CD3_HLA_DR3Mea: '1',
          CD4_CD25_CD127lowMea: '1',
          CD19_Note: '1',
          CD3_Note: '1',
          CD4_Note: '1',
          CD8_Note: '1',
          CD16_56Note: '1',
          LYMPH_Note: '1',
          CD19Note: '1',
          CD3Note: '1',
          CD4Note: '1',
          CD8Note: '1',
          CD4CD8Note: '1',
          CD56Note: '1',
          CD3_CD8__Note: '1',
          CD3_CD8_Note: '1',
          CD3_CD4__Note: '1',
          CD3_CD4_Note: '1',
          CD3_CD16_56_Note: '1',
          CD3_CD16_56Note: '1',
          CD3_CD19__Note: '1',
          CD3_CD19_Note: '1',
          CD8_CD28_Note: '1',
          CD20_Note: '1',
          HLA_DR_Note: '1',
          CD3_HLA_DR1Note: '1',
          CD3_HLA_DR2Note: '1',
          CD3_HLA_DR3Note: '1',
          CD4_CD25_CD127lowNote: '1',
        },
      ],

      UrineRoutine: [
        {
          UPH: '1',
          UGLU: '1',
          LEU: '1',
          ERY: '1',
          NIT: '1',
          BIL: '1',
          USG: '1',
          KET: '1',
          BLD: '1',
          PRO: '1',
          UBG: '1',
          COL: '1',
          CLA: '1',
          UPHMea: '1',
          UGLUMea: '1',
          LEUMea: '1',
          ERYMea: '1',
          NITMea: '1',
          BILMea: '1',
          USGMea: '1',
          KETMea: '1',
          BLDMea: '1',
          PROMea: '1',
          UBGMea: '1',
          COLMea: '1',
          CLAMea: '1',
          UPHNote: '1',
          UGLUNote: '1',
          LEUNote: '1',
          ERYNote: '1',
          NITNote: '1',
          BILNote: '1',
          USGNote: '1',
          KETNote: '1',
          BLDNote: '1',
          PRONote: '1',
          UBGNote: '1',
          COLNote: '1',
          CLANote: '1',
        },
        {
          UPH: '1',
          UGLU: '1',
          LEU: '1',
          ERY: '1',
          NIT: '1',
          BIL: '1',
          USG: '1',
          KET: '1',
          BLD: '1',
          PRO: '1',
          UBG: '1',
          COL: '1',
          CLA: '1',
          UPHMea: '1',
          UGLUMea: '1',
          LEUMea: '1',
          ERYMea: '1',
          NITMea: '1',
          BILMea: '1',
          USGMea: '1',
          KETMea: '1',
          BLDMea: '1',
          PROMea: '1',
          UBGMea: '1',
          COLMea: '1',
          CLAMea: '1',
          UPHNote: '1',
          UGLUNote: '1',
          LEUNote: '1',
          ERYNote: '1',
          NITNote: '1',
          BILNote: '1',
          USGNote: '1',
          KETNote: '1',
          BLDNote: '1',
          PRONote: '1',
          UBGNote: '1',
          COLNote: '1',
          CLANote: '1',
        },
        {
          UPH: '1',
          UGLU: '1',
          LEU: '1',
          ERY: '1',
          NIT: '1',
          BIL: '1',
          USG: '1',
          KET: '1',
          BLD: '1',
          PRO: '1',
          UBG: '1',
          COL: '1',
          CLA: '1',
          UPHMea: '1',
          UGLUMea: '1',
          LEUMea: '1',
          ERYMea: '1',
          NITMea: '1',
          BILMea: '1',
          USGMea: '1',
          KETMea: '1',
          BLDMea: '1',
          PROMea: '1',
          UBGMea: '1',
          COLMea: '1',
          CLAMea: '1',
          UPHNote: '1',
          UGLUNote: '1',
          LEUNote: '1',
          ERYNote: '1',
          NITNote: '1',
          BILNote: '1',
          USGNote: '1',
          KETNote: '1',
          BLDNote: '1',
          PRONote: '1',
          UBGNote: '1',
          COLNote: '1',
          CLANote: '1',
        },
        {
          UPH: '1',
          UGLU: '1',
          LEU: '1',
          ERY: '1',
          NIT: '1',
          BIL: '1',
          USG: '1',
          KET: '1',
          BLD: '1',
          PRO: '1',
          UBG: '1',
          COL: '1',
          CLA: '1',
          UPHMea: '1',
          UGLUMea: '1',
          LEUMea: '1',
          ERYMea: '1',
          NITMea: '1',
          BILMea: '1',
          USGMea: '1',
          KETMea: '1',
          BLDMea: '1',
          PROMea: '1',
          UBGMea: '1',
          COLMea: '1',
          CLAMea: '1',
          UPHNote: '1',
          UGLUNote: '1',
          LEUNote: '1',
          ERYNote: '1',
          NITNote: '1',
          BILNote: '1',
          USGNote: '1',
          KETNote: '1',
          BLDNote: '1',
          PRONote: '1',
          UBGNote: '1',
          COLNote: '1',
          CLANote: '1',
        },
      ],

      TumorMarker: [
        {
          CEA: '1',
          NSE: '1',
          pro_GPR: '1',
          CYFRA: '1',
          FERR: '1',
          AFP: '1',
          SCCA: '1',
          CEAMea: '1',
          NSEMea: '1',
          pro_GPRMea: '1',
          CYFRAMea: '1',
          FERRMea: '1',
          AFPMea: '1',
          SCCAMea: '1',
          CEANote: '1',
          NSENote: '1',
          pro_GPRNote: '1',
          CYFRANote: '1',
          FERRNote: '1',
          AFPNote: '1',
          SCCANote: '1',
        },
        {
          CEA: '1',
          NSE: '1',
          pro_GPR: '1',
          CYFRA: '1',
          FERR: '1',
          AFP: '1',
          SCCA: '1',
          CEAMea: '1',
          NSEMea: '1',
          pro_GPRMea: '1',
          CYFRAMea: '1',
          FERRMea: '1',
          AFPMea: '1',
          SCCAMea: '1',
          CEANote: '1',
          NSENote: '1',
          pro_GPRNote: '1',
          CYFRANote: '1',
          FERRNote: '1',
          AFPNote: '1',
          SCCANote: '1',
        },
      ],
      Lung: [
        {
          FVC_exp: '1',
          FEV1_FVC_exp: '1',
          MEF_exp: '1',
          MEF25_exp: '1',
          MEF50_exp: '1',
          MEF75_exp: '1',
          TLC_sb_exp: '1',
          RV_exp: '1',
          RV_TLC_exp: '1',
          VC_exp: '1',
          DLCO_ex_exp: '1',
          DLCO_sb_exp: '1',
          KCO_exp: '1',
          FVC_best: '1',
          FEV1_FVC_best: '1',
          MEF_best: '1',
          MEF25_best: '1',
          MEF50_best: '1',
          MEF75_best: '1',
          TLC_sb_best: '1',
          RV_best: '1',
          RV_TLC_best: '1',
          VC_best: '1',
          DLCO_ex_best: '1',
          DLCO_sb_best: '1',
          KCO_best: '1',
          FVC_ratio: '1',
          FEV1_FVC_ratio: '1',
          MEF_ratio: '1',
          MEF25_ratio: '1',
          MEF50_ratio: '1',
          MEF75_ratio: '1',
          TLC_sb_ratio: '1',
          RV_ratio: '1',
          RV_TLC_ratio: '1',
          VC_ratio: '1',
          DLCO_ex_ratio: '1',
          DLCO_sb_ratio: '1',
          KCO_ratio: '1',
          FVCMea: '1',
          FEV1_FVCMea: '1',
          MEFMea: '1',
          MEF25Mea: '1',
          MEF50Mea: '1',
          MEF75Mea: '1',
          TLC_sbMea: '1',
          RVMea: '1',
          RV_TLCMea: '1',
          VCMea: '1',
          DLCO_exMea: '1',
          DLCO_sbMea: '1',
          KCOMea: '1',
          FVCNote: '1',
          FEV1_FVCNote: '1',
          MEFNote: '1',
          MEF25Note: '1',
          MEF50Note: '1',
          MEF75Note: '1',
          TLC_sbNote: '1',
          RVNote: '1',
          RV_TLCNote: '1',
          VCNote: '1',
          DLCO_exNote: '1',
          DLCO_sbNote: '1',
          KCONote: '1',
        },
      ],
      pastHis: [
        {
          basDisHis: null,
          drink: false,
          drinkingHis: null,
          drug: true,
          drugUseHis: [
            {
              drugDose: '1g',
              drugName: '\u836f\u72691',
              duration: '1',
              key: 0,
            },
            {
              drugDose: '3g',
              drugName: '123',
              duration: '3',
              key: 1,
            },
          ],
          hormone: true,
          hormoneUseHis: [
            {
              drugDose: '2g',
              drugName: '123',
              duration: '1',
              key: 0,
            },
            {
              drugDose: '1g',
              drugName: '123',
              duration: '2',
              key: 1,
            },
          ],
          id: 4,
          infDisHis: '无',
          pid: 3,
          smoke: true,
          smokingHis: {
            smokeDayAvg: 1,
            smokeYearAvg: 1,
            stopSmoke: 1,
          },
          tumFamHis: null,
          tumHis: '大肠癌,鼻咽癌及头颈部肿瘤',
          tumor: true,
          tumorFam: false,
        },
      ],
    },
    msg: '病例的全部信息',
  };
  return res.json(result);
}

function upload(req: Request, res: Response, u: string) {
  const result = {
    code: 200,
    msg: '上传成功',
    path: ['static/2/1_hetuanceng_tx0.h5.png'],
  };
  return res.json(result);
}
function update(req: Request, res: Response, u: string) {
  const result = {
    code: 200,
    msg: '更新成功',
    id: 1,
  };
  return res.json(result);
}
function getdetail(req: Request, res: Response, u: string) {
  const result = {
    code: 200,
    msg: '获取成功',
    data: [
      {
        id: 1,
        age: 20,
        gender: '男',
        hospitalNumber: `hos22333`,
        idNumber: '12345',
        name: 'test',
        phoneNumber: '123456',
        patDia: '比较牛逼，还活着',
      },
      {
        id: 2,
        age: 20,
        gender: '男',
        hospitalNumber: `hos44999`,
        idNumber: '12346',
        name: 'test',
        phoneNumber: '123456',
        patDia: '比较牛逼，还活着',
      },
    ],
    total: 2,
  };
  return res.json(result);
}

function updateBloodRoutine(req: Request, res: Response, u: string) {
  if (req.body.id) {
    const result = {
      code: 200,
      msg: '更新成功',
      id: 5,
    };
    return res.json(result);
  } else {
    const result = {
      code: 200,
      msg: '添加成功',
      id: 5,
    };
    return res.json(result);
  }
}

function queryFollowUp(req: Request, res: Response, u: string) {
  const result = {
    code: 200,
    msg: '更新成功',
    data: [
      {
        hospitalNumber: '1008490694',
        id: 14,
        idNumber: '420221196310100903',
        name: '刘凤兰',
        nextFollowupTime: 'Tue, 04 Aug 2020 00:00:00 GMT',
        phoneNumber: '18064126114',
      },
      {
        hospitalNumber: '1008490694',
        id: 15,
        idNumber: '420221196310100903',
        name: '刘凤兰',
        nextFollowupTime: 'Tue, 04 Aug 2020 00:00:00 GMT',
        phoneNumber: '18064126114',
      },
    ],
    total: 2,
  };
  return res.json(result);
}

function alarmOff(req: Request, res: Response, u: string) {
  if (req.body.pid === 14) {
    const result = {
      code: 200,
      msg: '关闭成功',
    };
    return res.json(result);
  } else {
    const result = {
      code: 1231,
      msg: 'XX异常',
    };
    return res.json(result);
  }
}
export default {
  'GET /api/illCase/allinfo/find': getillCase,
  'POST /api/upload ': upload,
  'PUT /api/Patient/update ': update,
  'GET /api/illCase/find': getdetail,
  'PUT /api/BloodRoutine/update ': updateBloodRoutine,
  'GET /api/illCase/followup': queryFollowUp,
  'PUT /api/illCase/alarmoff': alarmOff,
  'POST /api/Patient/add ': update,
};
